### ISSUE TITLE
Time scale?

### ISSUE THREAD

**Issue by dlogan** [lhilbert/ivma3#2]
Hi, this is not really an Issue, per se, just a question: There are references to "seconds" time scale in the output, but I can't find where a user inputs the time scale, or conversely frame rate.  Do the scripts grab this info from the metadata, or is there an assumption built? Thanks!

**Comment by lhilbert** [comment]
That's a perfectly valid question. It grabs it from the MetaData of the
video (or rather, it should if everything works).

If it's an issue, one could add an override option. But I don't want to
confuse people toi much...

**Comment by dlogan** [comment]
OK very good, thanks for the quick response.  I haven't found any problem with this, I'm just being (over)cautious.  I'll re-open if I discover any issue.

**Comment by lhilbert** [comment]
Great, happy I could help. Please don't hesitate to write if there's an
issue or questions.

Sent from my phone

On Mar 17, 2017 4:07 PM, "David Logan" <notifications@github.com> wrote:

OK very good, thanks for the quick response. I haven't found any problem
with this, I'm just being (over)cautious. I'll re-open if I discover any
issue.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lhilbert/ivma3/issues/2#issuecomment-287379965>, or mute
the thread
